name: Claude SDK CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: self-hosted  # Uses your self-hosted runner
    
    steps:
    - uses: actions/checkout@v3
      
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Lint
      run: npm run lint
    
    - name: Test
      run: npm test
      
    - name: Build
      run: npm run build
      
  deploy:
    needs: build  # Only run if build job succeeds
    if: github.ref == 'refs/heads/main'  # Only deploy from main branch
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy
      run: echo "Deploying to production..."
      # Add your actual deployment commands here